{{- if .Values.mcp.ingress.enabled -}}
{{- $svcName := include "firecrawl-mcp.componentName" (list . "mcp") -}}
{{- $svcPort := .Values.mcp.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "firecrawl-mcp.componentName" (list . "mcp") }}
  labels:
    {{- include "firecrawl-mcp.componentLabels" (list . "mcp") | nindent 4 }}
  {{- with .Values.mcp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.mcp.ingress.className }}
  ingressClassName: {{ .Values.mcp.ingress.className }}
  {{- end }}
  {{- with .Values.mcp.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.mcp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
